package dk.sfs.riskengine.persistence.domain;

public class DepthPoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depth_denmark.id
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depth_denmark.lat
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depth_denmark.lon
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    private Double lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depth_denmark.latp
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    private Double latp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depth_denmark.lonp
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    private Double lonp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depth_denmark.n
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    private Integer n;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depth_denmark.m
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    private Integer m;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depth_denmark.depth
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    private Double depth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depth_denmark.id
     *
     * @return the value of depth_denmark.id
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depth_denmark.id
     *
     * @param id the value for depth_denmark.id
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depth_denmark.lat
     *
     * @return the value of depth_denmark.lat
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depth_denmark.lat
     *
     * @param lat the value for depth_denmark.lat
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depth_denmark.lon
     *
     * @return the value of depth_denmark.lon
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    public Double getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depth_denmark.lon
     *
     * @param lon the value for depth_denmark.lon
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    public void setLon(Double lon) {
        this.lon = lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depth_denmark.latp
     *
     * @return the value of depth_denmark.latp
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    public Double getLatp() {
        return latp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depth_denmark.latp
     *
     * @param latp the value for depth_denmark.latp
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    public void setLatp(Double latp) {
        this.latp = latp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depth_denmark.lonp
     *
     * @return the value of depth_denmark.lonp
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    public Double getLonp() {
        return lonp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depth_denmark.lonp
     *
     * @param lonp the value for depth_denmark.lonp
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    public void setLonp(Double lonp) {
        this.lonp = lonp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depth_denmark.n
     *
     * @return the value of depth_denmark.n
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    public Integer getN() {
        return n;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depth_denmark.n
     *
     * @param n the value for depth_denmark.n
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    public void setN(Integer n) {
        this.n = n;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depth_denmark.m
     *
     * @return the value of depth_denmark.m
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    public Integer getM() {
        return m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depth_denmark.m
     *
     * @param m the value for depth_denmark.m
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    public void setM(Integer m) {
        this.m = m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depth_denmark.depth
     *
     * @return the value of depth_denmark.depth
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    public Double getDepth() {
        return depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depth_denmark.depth
     *
     * @param depth the value for depth_denmark.depth
     *
     * @mbggenerated Tue Nov 29 13:20:20 CET 2011
     */
    public void setDepth(Double depth) {
        this.depth = depth;
    }
}