package dk.sfs.riskengine.persistence.domain;

public class Vessel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.id
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.imo
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Integer imo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.mmsi
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Integer mmsi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Name_of_Ship
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private String nameOfShip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.ship_type_LR
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private String shipTypeLr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.ship_type_IWRAP
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private String shipTypeIwrap;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.LENGTH
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Double length;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.LPP
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private String lpp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.BMLD
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private String bmld;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Breadth
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Double breadth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Depth
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Double depth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Draught
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Double draught;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Displacement
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Double displacement;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Deadweight
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Double deadweight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Year_of_Build
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Integer yearOfBuild;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Callsign
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private String callsign;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Flag
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private String flag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Hull_Type
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private String hullType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.GT
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Integer gt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Speed
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Double speed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Total_KW_Main_Eng
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Integer totalKwMainEng;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Fuel_Capacity_1
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Double fuelCapacity1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Fuel_Capacity_2
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Double fuelCapacity2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Passengers
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Integer passengers;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Tanks
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Integer tanks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Gas_Capacity
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Double gasCapacity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.TEU
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Integer teu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Fuel_Type_1
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private String fuelType1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Fuel_Type_2
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private String fuelType2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Holds
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Integer holds;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Class
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private String class_;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Engines_RPM
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Integer enginesRpm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Engine_Type
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private String engineType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Ice_capable
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private String iceCapable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Keel_To_Mast_Height
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Double keelToMastHeight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Newbuilding_Price
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Double newbuildingPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Fuel_Consumption_Main_Engines
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Integer fuelConsumptionMainEngines;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Fuel_Consumption_Total
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Integer fuelConsumptionTotal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loyds_ships.Bollard_Pull
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	private Integer bollardPull;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.id
	 * @return  the value of loyds_ships.id
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.id
	 * @param id  the value for loyds_ships.id
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.imo
	 * @return  the value of loyds_ships.imo
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Integer getImo() {
		return imo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.imo
	 * @param imo  the value for loyds_ships.imo
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setImo(Integer imo) {
		this.imo = imo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.mmsi
	 * @return  the value of loyds_ships.mmsi
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Integer getMmsi() {
		return mmsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.mmsi
	 * @param mmsi  the value for loyds_ships.mmsi
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setMmsi(Integer mmsi) {
		this.mmsi = mmsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Name_of_Ship
	 * @return  the value of loyds_ships.Name_of_Ship
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public String getNameOfShip() {
		return nameOfShip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Name_of_Ship
	 * @param nameOfShip  the value for loyds_ships.Name_of_Ship
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setNameOfShip(String nameOfShip) {
		this.nameOfShip = nameOfShip == null ? null : nameOfShip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.ship_type_LR
	 * @return  the value of loyds_ships.ship_type_LR
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public String getShipTypeLr() {
		return shipTypeLr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.ship_type_LR
	 * @param shipTypeLr  the value for loyds_ships.ship_type_LR
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setShipTypeLr(String shipTypeLr) {
		this.shipTypeLr = shipTypeLr == null ? null : shipTypeLr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.ship_type_IWRAP
	 * @return  the value of loyds_ships.ship_type_IWRAP
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public String getShipTypeIwrap() {
		return shipTypeIwrap;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.ship_type_IWRAP
	 * @param shipTypeIwrap  the value for loyds_ships.ship_type_IWRAP
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setShipTypeIwrap(String shipTypeIwrap) {
		this.shipTypeIwrap = shipTypeIwrap == null ? null : shipTypeIwrap.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.LENGTH
	 * @return  the value of loyds_ships.LENGTH
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Double getLength() {
		return length;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.LENGTH
	 * @param length  the value for loyds_ships.LENGTH
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setLength(Double length) {
		this.length = length;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.LPP
	 * @return  the value of loyds_ships.LPP
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public String getLpp() {
		return lpp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.LPP
	 * @param lpp  the value for loyds_ships.LPP
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setLpp(String lpp) {
		this.lpp = lpp == null ? null : lpp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.BMLD
	 * @return  the value of loyds_ships.BMLD
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public String getBmld() {
		return bmld;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.BMLD
	 * @param bmld  the value for loyds_ships.BMLD
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setBmld(String bmld) {
		this.bmld = bmld == null ? null : bmld.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Breadth
	 * @return  the value of loyds_ships.Breadth
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Double getBreadth() {
		return breadth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Breadth
	 * @param breadth  the value for loyds_ships.Breadth
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setBreadth(Double breadth) {
		this.breadth = breadth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Depth
	 * @return  the value of loyds_ships.Depth
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Double getDepth() {
		return depth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Depth
	 * @param depth  the value for loyds_ships.Depth
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setDepth(Double depth) {
		this.depth = depth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Draught
	 * @return  the value of loyds_ships.Draught
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Double getDraught() {
		return draught;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Draught
	 * @param draught  the value for loyds_ships.Draught
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setDraught(Double draught) {
		this.draught = draught;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Displacement
	 * @return  the value of loyds_ships.Displacement
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Double getDisplacement() {
		return displacement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Displacement
	 * @param displacement  the value for loyds_ships.Displacement
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setDisplacement(Double displacement) {
		this.displacement = displacement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Deadweight
	 * @return  the value of loyds_ships.Deadweight
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Double getDeadweight() {
		return deadweight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Deadweight
	 * @param deadweight  the value for loyds_ships.Deadweight
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setDeadweight(Double deadweight) {
		this.deadweight = deadweight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Year_of_Build
	 * @return  the value of loyds_ships.Year_of_Build
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Integer getYearOfBuild() {
		return yearOfBuild;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Year_of_Build
	 * @param yearOfBuild  the value for loyds_ships.Year_of_Build
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setYearOfBuild(Integer yearOfBuild) {
		this.yearOfBuild = yearOfBuild;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Callsign
	 * @return  the value of loyds_ships.Callsign
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public String getCallsign() {
		return callsign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Callsign
	 * @param callsign  the value for loyds_ships.Callsign
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setCallsign(String callsign) {
		this.callsign = callsign == null ? null : callsign.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Flag
	 * @return  the value of loyds_ships.Flag
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public String getFlag() {
		return flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Flag
	 * @param flag  the value for loyds_ships.Flag
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setFlag(String flag) {
		this.flag = flag == null ? null : flag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Hull_Type
	 * @return  the value of loyds_ships.Hull_Type
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public String getHullType() {
		return hullType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Hull_Type
	 * @param hullType  the value for loyds_ships.Hull_Type
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setHullType(String hullType) {
		this.hullType = hullType == null ? null : hullType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.GT
	 * @return  the value of loyds_ships.GT
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Integer getGt() {
		return gt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.GT
	 * @param gt  the value for loyds_ships.GT
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setGt(Integer gt) {
		this.gt = gt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Speed
	 * @return  the value of loyds_ships.Speed
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Double getSpeed() {
		return speed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Speed
	 * @param speed  the value for loyds_ships.Speed
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setSpeed(Double speed) {
		this.speed = speed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Total_KW_Main_Eng
	 * @return  the value of loyds_ships.Total_KW_Main_Eng
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Integer getTotalKwMainEng() {
		return totalKwMainEng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Total_KW_Main_Eng
	 * @param totalKwMainEng  the value for loyds_ships.Total_KW_Main_Eng
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setTotalKwMainEng(Integer totalKwMainEng) {
		this.totalKwMainEng = totalKwMainEng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Fuel_Capacity_1
	 * @return  the value of loyds_ships.Fuel_Capacity_1
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Double getFuelCapacity1() {
		return fuelCapacity1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Fuel_Capacity_1
	 * @param fuelCapacity1  the value for loyds_ships.Fuel_Capacity_1
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setFuelCapacity1(Double fuelCapacity1) {
		this.fuelCapacity1 = fuelCapacity1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Fuel_Capacity_2
	 * @return  the value of loyds_ships.Fuel_Capacity_2
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Double getFuelCapacity2() {
		return fuelCapacity2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Fuel_Capacity_2
	 * @param fuelCapacity2  the value for loyds_ships.Fuel_Capacity_2
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setFuelCapacity2(Double fuelCapacity2) {
		this.fuelCapacity2 = fuelCapacity2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Passengers
	 * @return  the value of loyds_ships.Passengers
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Integer getPassengers() {
		return passengers;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Passengers
	 * @param passengers  the value for loyds_ships.Passengers
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setPassengers(Integer passengers) {
		this.passengers = passengers;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Tanks
	 * @return  the value of loyds_ships.Tanks
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Integer getTanks() {
		return tanks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Tanks
	 * @param tanks  the value for loyds_ships.Tanks
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setTanks(Integer tanks) {
		this.tanks = tanks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Gas_Capacity
	 * @return  the value of loyds_ships.Gas_Capacity
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Double getGasCapacity() {
		return gasCapacity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Gas_Capacity
	 * @param gasCapacity  the value for loyds_ships.Gas_Capacity
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setGasCapacity(Double gasCapacity) {
		this.gasCapacity = gasCapacity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.TEU
	 * @return  the value of loyds_ships.TEU
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Integer getTeu() {
		return teu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.TEU
	 * @param teu  the value for loyds_ships.TEU
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setTeu(Integer teu) {
		this.teu = teu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Fuel_Type_1
	 * @return  the value of loyds_ships.Fuel_Type_1
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public String getFuelType1() {
		return fuelType1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Fuel_Type_1
	 * @param fuelType1  the value for loyds_ships.Fuel_Type_1
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setFuelType1(String fuelType1) {
		this.fuelType1 = fuelType1 == null ? null : fuelType1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Fuel_Type_2
	 * @return  the value of loyds_ships.Fuel_Type_2
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public String getFuelType2() {
		return fuelType2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Fuel_Type_2
	 * @param fuelType2  the value for loyds_ships.Fuel_Type_2
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setFuelType2(String fuelType2) {
		this.fuelType2 = fuelType2 == null ? null : fuelType2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Holds
	 * @return  the value of loyds_ships.Holds
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Integer getHolds() {
		return holds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Holds
	 * @param holds  the value for loyds_ships.Holds
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setHolds(Integer holds) {
		this.holds = holds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Class
	 * @return  the value of loyds_ships.Class
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public String getClass_() {
		return class_;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Class
	 * @param class_  the value for loyds_ships.Class
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setClass_(String class_) {
		this.class_ = class_ == null ? null : class_.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Engines_RPM
	 * @return  the value of loyds_ships.Engines_RPM
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Integer getEnginesRpm() {
		return enginesRpm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Engines_RPM
	 * @param enginesRpm  the value for loyds_ships.Engines_RPM
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setEnginesRpm(Integer enginesRpm) {
		this.enginesRpm = enginesRpm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Engine_Type
	 * @return  the value of loyds_ships.Engine_Type
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public String getEngineType() {
		return engineType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Engine_Type
	 * @param engineType  the value for loyds_ships.Engine_Type
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setEngineType(String engineType) {
		this.engineType = engineType == null ? null : engineType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Ice_capable
	 * @return  the value of loyds_ships.Ice_capable
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public String getIceCapable() {
		return iceCapable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Ice_capable
	 * @param iceCapable  the value for loyds_ships.Ice_capable
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setIceCapable(String iceCapable) {
		this.iceCapable = iceCapable == null ? null : iceCapable.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Keel_To_Mast_Height
	 * @return  the value of loyds_ships.Keel_To_Mast_Height
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Double getKeelToMastHeight() {
		return keelToMastHeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Keel_To_Mast_Height
	 * @param keelToMastHeight  the value for loyds_ships.Keel_To_Mast_Height
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setKeelToMastHeight(Double keelToMastHeight) {
		this.keelToMastHeight = keelToMastHeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Newbuilding_Price
	 * @return  the value of loyds_ships.Newbuilding_Price
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Double getNewbuildingPrice() {
		return newbuildingPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Newbuilding_Price
	 * @param newbuildingPrice  the value for loyds_ships.Newbuilding_Price
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setNewbuildingPrice(Double newbuildingPrice) {
		this.newbuildingPrice = newbuildingPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Fuel_Consumption_Main_Engines
	 * @return  the value of loyds_ships.Fuel_Consumption_Main_Engines
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Integer getFuelConsumptionMainEngines() {
		return fuelConsumptionMainEngines;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Fuel_Consumption_Main_Engines
	 * @param fuelConsumptionMainEngines  the value for loyds_ships.Fuel_Consumption_Main_Engines
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setFuelConsumptionMainEngines(Integer fuelConsumptionMainEngines) {
		this.fuelConsumptionMainEngines = fuelConsumptionMainEngines;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Fuel_Consumption_Total
	 * @return  the value of loyds_ships.Fuel_Consumption_Total
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Integer getFuelConsumptionTotal() {
		return fuelConsumptionTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Fuel_Consumption_Total
	 * @param fuelConsumptionTotal  the value for loyds_ships.Fuel_Consumption_Total
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setFuelConsumptionTotal(Integer fuelConsumptionTotal) {
		this.fuelConsumptionTotal = fuelConsumptionTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loyds_ships.Bollard_Pull
	 * @return  the value of loyds_ships.Bollard_Pull
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public Integer getBollardPull() {
		return bollardPull;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loyds_ships.Bollard_Pull
	 * @param bollardPull  the value for loyds_ships.Bollard_Pull
	 * @mbggenerated  Fri Nov 25 11:29:18 CET 2011
	 */
	public void setBollardPull(Integer bollardPull) {
		this.bollardPull = bollardPull;
	}
}