package dk.sfs.riskengine.persistence.mapper;

import dk.sfs.riskengine.persistence.domain.Static;

public interface StaticMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_info_memory
     *
     * @mbggenerated Fri Jan 06 13:36:21 CET 2012
     */
    int insert(Static record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_info_memory
     *
     * @mbggenerated Fri Jan 06 13:36:21 CET 2012
     */
    int insertSelective(Static record);
    
    Static selectByMmsi(int mmsi);
}